### PR TITLE
Make code blocks scroll horizontally

### PR DESCRIPTION
**Pull request by mfcovington**

### CODE REVIEW

**Comment by jnmaloof** [comment]
Thanks

**Comment by jnmaloof** [comment]
Do you know if there is a way to have the scrollbars always display (when there is overflow)?  i.e. if you don't know there is the possibility of scrolling it just looks like it is cut off.

**Comment by mfcovington** [comment]
Not showing the scrollbar is a 'feature' of OS X. I'll override it for you.

**Comment by mfcovington** [comment]
See PR #5 for fix.

**Comment by jnmaloof** [comment]
Thanks!

Julin Maloof
Professor
Department of Plant Biology
1 Shields Ave
University of California, Davis
Davis, CA 95616
(530) 752 8077

**Pull request merged**
